// Package testutils contains a mock influxdb client and test data.
package testutils

// The test data is generated by intercepting inputs and outputs of rawQuery()
// function in src/metricsclient/raw_query.go
